#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (set = 0, binding = 0, rgba8) uniform image2D uOutput;

void main() {
  ivec2 extent = imageSize(uOutput);
  ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

  if (pixelCoords.x < extent.x && pixelCoords.y < extent.y) {
    vec2 interp = vec2(pixelCoords) / vec2(extent);
    vec4 color = vec4(interp, 0.0, 1.0);
    imageStore(uOutput, pixelCoords, color);
  }
}
